### ISSUE TITLE
Example of a remote schema with a local delegation to a mutation?

### ISSUE THREAD

**Issue by djnym** [gmac/schema-stitching-demos#35]
I've been trying to update an older version of graphql-tools to the newest version and running into an issue which I can't find in any documentation, so hoping you might be able to add a simple worked example.  The use case is a remote schema which I want to override a mutation for and then delegate to the remote schema's mutation.  So the flow would be when the mutation is called, it flows into the local code which then uses delegateToSchema against the remote schema.  When I try to do this I end up with the error `Error: "Mutation" defined in resolvers, but not in schema` so I must be doing something wrong, but the official docs don't really have a worked example and while you have a `custom-merge-resolvers` that's not quite it either, as that's working only with local schema's and not a remote schema with an executor.

**Comment by djnym** [comment]
I tried starting with your mutations-and-subscriptions example because it most closely did what I wanted to do, and made a few modifications to try to have my own resolver called and then delegate to the remote schema.   I did these here https://github.com/djnym/stitching-issue
It's not working as I would expect which would that I would see a printout that the local code ran, and then the remote code ran, but I do not.   Any ideas?

**Comment by djnym** [comment]
FYI, I managed to get something working in my repo.  I still think it would be a good addition here as it shows stitching a remote schema and adding a local resolver which delegates.  Feel free to use anything from my repo.   This repo is pretty awesome BTW, as worked examples are better than the documentation of the library.

**Comment by gmac** [comment]
Sorry for the slow reply. I took a quick look at your linked example and it looks fine for what it is, though I don't fully understand your goals. Ultimately we'd like to remove knowledge of schema implementations from the gateway and keep it as a dumb router. I assume you have your own very specific reasons for the gateway sharing responsibility with a subservice. Otherwise, this isn't the type of pattern that I'd generally encourage.

If you do feel that it's a general use case that I'm missing though, contributions are of course welcome. This subject feels most closely related to the topic of [custom merge resolvers](https://github.com/gmac/schema-stitching-handbook/tree/master/custom-merge-resolvers), although it's slightly unique in that you're customizing the resolution of a one-off field rather than the accessor for a type.
