### ISSUE TITLE
Fetch merged type in parallel

### ISSUE THREAD

**Issue by mattfysh** [gmac/schema-stitching-demos#40]
Hey gmac, thanks for the quality content! 

I'm working on type merging and was wondering why the subschemas cannot be executed in parallel if the ID of the type is known upfront (ie included in the initial user query). I'm running through the basic example on this page https://the-guild.dev/graphql/tools/docs/schema-stitching/stitch-type-merging

What I've noticed is that the gateway schema waits for the response from users service before calling out to the posts service. Given that the user ID is already known, why does the post service have to wait until the user service returns the same ID that was originally included? thanks!

**Comment by gmac** [comment]
@mattfysh – sorry for the slow reply. Short answer is invalidation. We have to get a result for a valid record within the graph before stitching kicks in, rather than stitching against an untrusted ID. In general, the root query is just a plain old GraphQL request... stitching action only kicks in once we have a trusted origin object to work from.
